Metrics/LineLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 30
